### ISSUE TITLE
Paging in pipe example

### ISSUE THREAD

**Issue by kspeakman** [lorenzofox3/smart-table-website#17]
On this line:
https://github.com/lorenzofox3/smart-table-website/blob/gh-pages/sections/pipe/markup.html#L168

It currently has `st-item-by-page="10"`. Should be `st-items-by-page="10"`. Notice the missing **s**. If I run the current example, the attribute is not recognized and its value is ignored. I tried setting it to 5, for instance, and paging still skipped 10 at a time. Spent a while trying to figure out why. I eventually looked at other examples to figure out the attribute name was a typo.

**Comment by lorenzofox3** [comment]
You are correct, thanks a lot! 
Actually using 10 as value for this example is not a good choice as it is the default value, I should change it to something different
