### ISSUE TITLE
st-sort-default needs to have a non-empty value for ascending

### ISSUE THREAD

**Issue by ianhd** [lorenzofox3/smart-table-website#19]
For default sorting, simply doing `<th st-sort="myProperty" st-sort-default>` will not sort the data by that column. If I do `st-sort-default="reverse"`, that correctly sorts in reverse. As a fix, I tried doing `st-sort-default="whatever"` and that did the trick. It doesn't seem to matter what value is used, just as long as it's provided and it's not "reverse" for the default ascending order.

**Comment by blaise-io** [comment]
I concur, I had to look at the source code to see how this works and decided on `st-sort-default="true"`. 

It would be helpful to have this properly documented.
