### ISSUE TITLE
"Random" errors on iOS

### ISSUE THREAD

**Issue by jonnysmith1981** [lorenzofox3/smart-table-website#29]
When we access our webapp which includes smart-table, on iOS-based devices, we intermittently get these errors:

angular.min.js:89:239Error: [$compile:ctreq] http://errors.angularjs.org/1.3.0-beta.5/$compile/ctreq?p0=stTable&p1=stPagination
http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:6:461
K@http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:50:280
H@http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:53:296
f@http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:46:315
f@http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:46:332
f@http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:46:332
f@http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:46:332
H@http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:53:201
f@http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:46:315
http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:45:592
http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:47:210
z@http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:50:449
http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:193:192
$digest@http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:106:313
$apply@http://172.22.201.3/activehmobile/JS/AngularJS/angular.min.js:109:294
http://172.22.201.3/activehmobile/JS/AngularJS/angular-touch.min.js:11:389
dispatch@http://172.22.201.3/activehmobile/JS/jquery.mobile-1.3.1/jquery-1.9.1.min.js:2:28520
handle@http://172.22.201.3/activehmobile/JS/jquery.mobile-1.3.1/jquery-1.9.1.min.js:2:25225 <div class="pagination ng-isolate-scope" st-pagination="" st-items-by-page="10" st-displayed-pages="7">
angular.min.js:89:239

Are there any known issues with smart-table on iOS?

**Comment by lorenzofox3** [comment]
nope, but if you follow the first link on your stack trace you'll find what the error is about:
- you are using stPagination directive without stTable on a parent element ?
- if not, maybe the version of angular you are using has a bug (try other versions and check angular change log for more details)

**Comment by jonnysmith1981** [comment]
I can rule out the first one. This problem does not occur on Android devices or on desktop browsers and all stPagination directives are in the tfoot section of tables decorated with stTable.

I'll try a later version of angular. (Since the one we are currently using is 1.3.0b5 - oooops)

**Comment by jonnysmith1981** [comment]
I would like to close this issue for a couple of reasons:

1) I logged it in the wrong github repo
2) Based on lorenzofox3's advice, after I upgraded from AngularJS 1.3.0b5 to 1.3.0 Release, we are unable to reproduce the errors.
