### ISSUE TITLE
Doc error

### ISSUE THREAD

**Issue by martende** [lorenzofox3/smart-table-website#32]
https://github.com/lorenzofox3/smart-table-website/blob/gh-pages/index.html#L1001

is not shown. tested on chrome.

**Comment by lorenzofox3** [comment]
![screen shot 2015-04-14 at 11 16 12](https://cloud.githubusercontent.com/assets/2402022/7130286/bf932e8c-e297-11e4-9815-61cd8b1c5d00.png)  ?

**Comment by martende** [comment]
I am about template val in <pre> tag . it is not shown.
![screen](https://cloud.githubusercontent.com/assets/1508729/7130825/e6fb5c4a-e276-11e4-9c25-378652ce7abf.png)

**Comment by lorenzofox3** [comment]
ah thanks !
