### ISSUE TITLE
stSearch Documentation Correction

### ISSUE THREAD

**Issue by kenhowardpdx** [lorenzofox3/smart-table-website#35]
In various places in the documentation it appears that the value of `st-search` is a string. But in reality it should be an expression that evaluates to a string.

I would update the documentation and submit a PR, but the documentation is missing.

Example:

```
Change this:
<input st-search="firstName" placeholder="search for firstname" class="input-sm form-control" type="search"/>

to this:
<input st-search="'firstName'" placeholder="search for firstname" class="input-sm form-control" type="search"/>
```

subtle change. Added single-quotes around the `firstName` key.

**Comment by lorenzofox3** [comment]
I don't think it is true, what is the version you are using ? 
Refere to the [change log](https://github.com/lorenzofox3/Smart-Table/blob/master/changeLog.md) (v2.0..0)

**Comment by kenhowardpdx** [comment]
@lorenzofox3 Good point. I'm using 1.4.13 :smile: Not going to upgrade though.
