### ISSUE TITLE
Wrong directive spelling

### ISSUE THREAD

**Issue by LGLabGreg** [lorenzofox3/smart-table-website#38]
Hi,

Thanks for that directive, best of all the ones I've tried :-)

I think there's a spelling mistake for the stInputEvent directive declaration:

Current:
select stInputEvent="change"...
Should be:
select st-input-event="change"...

Cheers,
Greg

**Comment by lorenzofox3** [comment]
good catch, will be corrected on next build

**Comment by kenhowardpdx** [comment]
I was just going to suggest this same change... Why hasn't this change been deployed to the site?

**Comment by lorenzofox3** [comment]
because I need to run gulp build and push the result of the build

**Comment by kenhowardpdx** [comment]
:+1:
